name = "Simply Craftmine"
author = "cassiancc"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2816cca540148fada3d09f25f6df2b1af84e77030b556f8a8e46711aa496e487"

[versions]
fabric = "0.18.4"
minecraft = "25w14craftmine"
