name = "Simply Craftmine"
author = "cassiancc"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "504f9d461d1a92d8e7d937774b9cb4cfe837fe89f6d1a66b99f7a12849673d9a"

[versions]
fabric = "0.16.12"
minecraft = "25w14craftmine"
