name = "Simply Craftmine"
author = "cassiancc"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db00e1beff56a07d13cf44eee5b2e5bfd0e948b361f331ad511e09bb1c0b773f"

[versions]
fabric = "0.16.13"
minecraft = "25w14craftmine"
