name = "Simply Craftmine"
author = "cassiancc"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcb50c5b7c15dc79f88b69ad691499b536c24bf3fea138f82b3a89d39da8c28d"

[versions]
fabric = "0.16.13"
minecraft = "25w14craftmine"
