name = "Simply Craftmine"
author = "cassiancc"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83f909eeebe3e1e237d0898405bd834c58b1a2f0e2c46a8d8b76eb371b410951"

[versions]
fabric = "0.16.12"
minecraft = "25w14craftmine"
