name = "Simply Craftmine"
author = "cassiancc"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5462062376bed564b7f6acbe7a424c0ec9c98536e43ac5c3322f92728eb95e56"

[versions]
fabric = "0.16.13"
minecraft = "25w14craftmine"
